spring.application.name=web-ai-stm32

# 服务器配置
server.port=8080

# Netty服务器配置
netty.port=9000

# 日志配置
logging.level.root=INFO
logging.level.com.lihe=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Jackson配置
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
